import { SeoPageData } from "./seoPages";

export const SEO_PAGES_2: SeoPageData[] = [
  {
    slug: "email-signature-maker",
    title: "Maker",
    metaTitle: "Free Email Signature Maker — Create Yours in 60 Seconds | NeatStamp",
    metaDescription: "Make a professional email signature for free. No account, no paywall. Works in Gmail, Outlook & 30+ clients. The easiest email signature maker online.",
    h1: "Free Email Signature Maker",
    intro: "Looking for a simple email signature maker? NeatStamp lets you create a professional, Outlook-proof email signature in 60 seconds. No account needed, no credit card, no hidden fees. Just fill in your details, pick a design, and copy-paste into your email client.",
    steps: [
      { title: "Enter your information", description: "Add your name, job title, company, phone, email, website, and social media links." },
      { title: "Choose your style", description: "Pick from 5 free signature designs. Customize colors to match your brand." },
      { title: "Make it yours", description: "Upload your photo or company logo. Add a Calendly booking link or promotional banner." },
      { title: "Copy and use", description: "One click to copy. Paste into Gmail, Outlook, Apple Mail, or any email client." },
    ],
    features: [
      "Create unlimited email signatures for free",
      "No account or signup required",
      "Works in Gmail, Outlook, Apple Mail, Yahoo & 30+ email clients",
      "Outlook-proof HTML — guaranteed to render correctly",
      "Add photos, logos, social media links, and booking buttons",
      "Mobile-responsive signatures that look great on any device",
      "Privacy-first — your data never leaves your browser",
    ],
    faq: [
      { q: "Is this email signature maker really free?", a: "Yes. NeatStamp is completely free for creating professional email signatures. No account needed, no credit card, no time limit. You can create, customize, and copy your signature without paying anything." },
      { q: "What's the difference between a signature maker and a signature generator?", a: "They're the same thing. Whether you call it a maker, generator, creator, or builder — NeatStamp does it all. Create your professional email signature in 60 seconds." },
      { q: "Can I make multiple signatures?", a: "With the free tier, you can create as many signatures as you want — just design a new one each time. With Pro ($5/month), you can save and manage multiple signatures." },
    ],
  },
  {
    slug: "professional-email-signature",
    title: "Professional",
    metaTitle: "Professional Email Signature — Free Generator & Examples | NeatStamp",
    metaDescription: "Create a professional email signature that impresses. Free templates, examples, and best practices. Works in Gmail & Outlook. No signup needed.",
    h1: "Create a Professional Email Signature",
    intro: "Your email signature is seen thousands of times per year. A professional signature builds trust, reinforces your brand, and makes every email count. NeatStamp helps you create one in 60 seconds — with the right layout, fonts, and formatting that email clients actually render correctly.",
    steps: [
      { title: "Start with the essentials", description: "Full name, job title, company name, phone number, and email. Keep it clean — less is more." },
      { title: "Add your brand elements", description: "Upload your headshot or company logo. Choose colors that match your brand identity." },
      { title: "Include social proof", description: "Add LinkedIn, your company website, and any other relevant professional links." },
      { title: "Export and install", description: "Copy your signature and paste it into Gmail, Outlook, or your preferred email client." },
    ],
    features: [
      "Professional templates designed by email marketing experts",
      "Proper hierarchy: name > title > contact > social links",
      "Web-safe fonts that render consistently across all email clients",
      "Optimized image sizes for fast loading and no spam triggers",
      "Table-based HTML that works in Outlook, Gmail, and Apple Mail",
      "Mobile-responsive design for professional appearance on phones",
    ],
    faq: [
      { q: "What makes an email signature look professional?", a: "A professional email signature has a clear hierarchy (name, title, company, contact info), uses consistent branding (colors, logo), sticks to 3-4 lines of contact info, uses web-safe fonts, and includes a professional headshot or company logo." },
      { q: "Should I include a photo in my professional signature?", a: "Yes — signatures with photos get 32% more responses. Use a professional headshot, not a casual photo. Keep it small (around 80x80 pixels) so it doesn't trigger spam filters." },
      { q: "How many social links should I include?", a: "Stick to 2-3 relevant professional links. LinkedIn is essential. Add your company website and one other platform relevant to your industry. Too many links look cluttered." },
    ],
  },
  {
    slug: "email-signature-with-logo",
    title: "With Logo",
    metaTitle: "Email Signature with Logo — Free Generator | NeatStamp",
    metaDescription: "Create a free email signature with your company logo or headshot. Upload your logo, customize colors, copy and paste. Works in Gmail & Outlook.",
    h1: "Create an Email Signature with Logo",
    intro: "A logo in your email signature instantly makes your emails look more professional and trustworthy. NeatStamp makes it easy — upload your company logo or headshot, and we'll format it perfectly for every email client, including Outlook.",
    steps: [
      { title: "Upload your logo", description: "Click the photo upload area and select your company logo or headshot. Supports JPG, PNG up to 2MB. We'll resize it automatically." },
      { title: "Enter your details", description: "Add your name, title, company, and contact information alongside your logo." },
      { title: "Choose a layout", description: "Pick a template that positions your logo exactly how you want — left-aligned, above your name, or in a circular frame." },
      { title: "Copy to your email", description: "Your logo is embedded in the signature HTML. Copy and paste into Gmail, Outlook, or any email client." },
    ],
    features: [
      "Upload company logo or professional headshot",
      "Automatic image resizing and optimization",
      "Logo won't appear as an attachment in Outlook",
      "Circular or square photo framing options",
      "Brand color matching with your logo",
      "Crisp, non-blurry logo display across all email clients",
    ],
    faq: [
      { q: "Will my logo show up in Outlook?", a: "Yes. NeatStamp uses hosted image URLs instead of base64 encoding, which means your logo displays correctly in Outlook without appearing as an email attachment." },
      { q: "What size should my logo be?", a: "For best results, upload a square image at least 200x200 pixels. NeatStamp will automatically resize it to the optimal size for email signatures (typically 70-90px)." },
      { q: "Can I use a transparent PNG logo?", a: "Yes. PNG logos with transparent backgrounds work great and look professional against any email background color." },
    ],
  },
  {
    slug: "email-signature-design",
    title: "Design",
    metaTitle: "Email Signature Design — Free Templates & Ideas | NeatStamp",
    metaDescription: "Design a stunning email signature for free. 8 modern templates, custom colors, professional layouts. No design skills needed. Works in Gmail & Outlook.",
    h1: "Email Signature Design Made Easy",
    intro: "Great email signature design doesn't require a graphic designer. NeatStamp offers professionally designed templates with customizable colors, layouts, and typography — all optimized to render perfectly in every email client. Pick a design, make it yours, done.",
    steps: [
      { title: "Browse designs", description: "Choose from 8 signature designs: Minimal, Modern, Corporate, Creative, Bold, Elegant, Startup, and Compact." },
      { title: "Customize colors", description: "Match your brand with custom primary and accent colors. Real-time preview shows every change instantly." },
      { title: "Add your content", description: "Fill in your details, upload your photo, add social links. The design adapts automatically." },
      { title: "Export your design", description: "Copy your designed signature as email-ready HTML. Works in every email client." },
    ],
    features: [
      "8 professionally designed signature templates",
      "Custom color picker for brand matching",
      "Real-time design preview as you edit",
      "Optimized typography with web-safe fonts",
      "Consistent design across desktop and mobile",
      "No design skills or HTML knowledge needed",
    ],
    faq: [
      { q: "What's the best email signature design?", a: "The best designs are clean and simple. Use 2-3 colors max, include your essential contact info, and don't overcrowd with icons or banners. Our Minimal and Modern templates are the most popular choices." },
      { q: "What size should an email signature be?", a: "Aim for a maximum width of 600px and height of 150px. This ensures your signature looks good on both desktop and mobile without taking up too much space in the email." },
      { q: "Can I customize the design beyond the templates?", a: "Yes. Every template lets you customize primary and accent colors, choose which fields to show or hide, and add optional elements like Calendly buttons or promotional banners." },
    ],
  },
  {
    slug: "html-email-signature",
    title: "HTML",
    metaTitle: "HTML Email Signature Generator — Outlook-Safe Code | NeatStamp",
    metaDescription: "Generate HTML email signatures that work in every email client. Table-based, inline CSS, Outlook-proof. Free HTML code — just copy and paste.",
    h1: "HTML Email Signature Generator",
    intro: "Need clean HTML for your email signature? NeatStamp generates table-based HTML with inline CSS — the only approach that renders correctly in Outlook, Gmail, Apple Mail, and every other email client. No coding required. Get your HTML code with one click.",
    steps: [
      { title: "Design your signature", description: "Use our visual editor to create your signature — no HTML knowledge needed." },
      { title: "Click the code button", description: "Click the '</>' button next to Copy Signature to view the generated HTML code." },
      { title: "Copy the HTML", description: "Click 'Copy HTML' to get the raw HTML code on your clipboard." },
      { title: "Use anywhere", description: "Paste the HTML into your email client settings, CRM, or email marketing platform." },
    ],
    features: [
      "Clean, table-based HTML layout (not div-based)",
      "All CSS is inline — no external stylesheets",
      "Outlook-safe: uses only HTML/CSS that Microsoft Word's engine supports",
      "No JavaScript or external dependencies",
      "Optimized image references (hosted URLs, not base64)",
      "Valid HTML that passes email client validators",
    ],
    faq: [
      { q: "Why does my HTML signature break in Outlook?", a: "Outlook uses Microsoft Word's HTML engine, which doesn't support modern CSS like flexbox, grid, or float. NeatStamp generates table-based layouts with inline CSS — the only approach that works reliably in every Outlook version." },
      { q: "Can I edit the HTML code manually?", a: "Yes. Click the code button to view and copy the raw HTML. You can modify it in any text editor. Just be careful not to use CSS properties that Outlook doesn't support." },
      { q: "Will this HTML work in email marketing platforms?", a: "Yes. The HTML is compatible with Mailchimp, HubSpot, SendGrid, and other email platforms. Just paste it into your signature or template settings." },
    ],
  },
  {
    slug: "best-email-signature-generator",
    title: "Best Generator",
    metaTitle: "Best Email Signature Generator (2026) — Free & Compared | NeatStamp",
    metaDescription: "Looking for the best email signature generator? We compared NeatStamp vs WiseStamp vs MySignature vs HubSpot. See which is truly free and works in Outlook.",
    h1: "Best Email Signature Generator in 2026",
    intro: "There are dozens of email signature generators — but most advertise as 'free' while hiding features behind paywalls. We tested them all. Here's an honest comparison of the best email signature generators in 2026, including which ones are actually free and which ones work in Outlook.",
    steps: [
      { title: "Try NeatStamp first", description: "Actually free. No account needed. Works in all email clients. Create your signature in 60 seconds." },
      { title: "Compare features", description: "Check our comparison table below to see how each generator stacks up on free features, Outlook support, and pricing." },
      { title: "Test in your email client", description: "The best generator is the one that works in YOUR email client. Create a signature and test it before committing." },
      { title: "Consider your needs", description: "Solo professional? Free tier is enough. Team? Look for central management features." },
    ],
    features: [
      "Honest comparison of 6+ email signature generators",
      "Actually free option with no paywall tricks",
      "Outlook compatibility testing for each generator",
      "Pricing comparison (free tiers vs paid plans)",
      "User review analysis from Trustpilot and G2",
      "Updated for 2026 with latest features and pricing",
    ],
    faq: [
      { q: "What is the best free email signature generator?", a: "NeatStamp is the best truly free option — no account required, no paywall, and Outlook-proof. HubSpot's generator is also free but limited to 12 templates and pushes you toward their CRM." },
      { q: "Is WiseStamp worth it?", a: "WiseStamp has 1.2 million users but 53% one-star reviews on Trustpilot. The main complaints are subscription traps, impossible cancellation, and continued billing after canceling. There are better alternatives." },
      { q: "Which generator works best with Outlook?", a: "NeatStamp generates table-based HTML with inline CSS — the gold standard for Outlook compatibility. Many other generators use div-based layouts that break in Outlook's rendering engine." },
    ],
  },
  {
    slug: "ai-email-signature-generator",
    title: "AI Generator",
    metaTitle: "AI Email Signature Generator — Smart Signatures in Seconds | NeatStamp",
    metaDescription: "Create an AI-powered email signature. Smart text suggestions, automatic formatting, professional layouts. Free AI email signature generator.",
    h1: "AI Email Signature Generator",
    intro: "Let AI help you create the perfect email signature. NeatStamp's AI-powered generator suggests professional titles, optimizes your layout, and ensures your signature looks great in every email client — all in under 60 seconds.",
    steps: [
      { title: "Enter your basics", description: "Just your name and company. AI suggests the rest — job title formatting, contact layout, social link placement." },
      { title: "AI optimizes your layout", description: "Our AI picks the best template and color scheme based on your industry and role." },
      { title: "Review and customize", description: "Fine-tune anything the AI suggested. You're always in control of the final result." },
      { title: "Copy your AI-crafted signature", description: "One click to copy your professionally optimized signature." },
    ],
    features: [
      "AI-suggested job title formatting",
      "Smart template recommendations based on your industry",
      "Automatic color scheme suggestions",
      "Optimized contact information hierarchy",
      "AI-powered professional bio suggestions",
      "Works with all email clients — Outlook, Gmail, Apple Mail",
    ],
    faq: [
      { q: "How does the AI email signature generator work?", a: "Our AI analyzes your name, job title, and industry to suggest the optimal signature layout, template, and color scheme. It formats your information for maximum professional impact while ensuring email client compatibility." },
      { q: "Is the AI signature generator free?", a: "Yes. The AI features are included in the free tier. Create an AI-optimized email signature without any account or payment." },
      { q: "Can I override the AI suggestions?", a: "Absolutely. The AI provides suggestions, but you have full control. Change any template, color, or layout at any time." },
    ],
  },
  {
    slug: "email-signature-outlook-365",
    title: "Outlook 365",
    metaTitle: "Email Signature for Outlook 365 & Microsoft 365 | NeatStamp — Free",
    metaDescription: "Create a perfect email signature for Outlook 365 / Microsoft 365. Guaranteed to work — no broken layouts. Free, no account needed. Copy and paste setup.",
    h1: "Email Signature for Outlook 365 (Microsoft 365)",
    intro: "Outlook 365 (now Microsoft 365) handles email signatures differently than classic Outlook. Whether you use the web app, desktop app, or mobile app, NeatStamp creates signatures that work perfectly across all Outlook 365 versions.",
    steps: [
      { title: "Create your signature", description: "Use NeatStamp's editor — every template is Outlook 365 compatible by default." },
      { title: "Copy your signature", description: "Click 'Copy Signature' for a rich-text copy that preserves all formatting." },
      { title: "Open Outlook 365 settings", description: "Web: Settings → View all Outlook settings → Mail → Compose and reply. Desktop: File → Options → Mail → Signatures." },
      { title: "Paste and save", description: "Create a new signature, paste your NeatStamp signature, and set it as default." },
    ],
    features: [
      "Works in Outlook 365 web, desktop, and mobile",
      "Compatible with Microsoft 365 Business and Enterprise",
      "Table-based HTML that Outlook 365 renders correctly",
      "No broken images or missing formatting",
      "Works with shared mailboxes and aliases",
      "Compatible with Outlook 365 signature policies",
    ],
    faq: [
      { q: "Does this work with the new Outlook for Windows?", a: "Yes. NeatStamp signatures work in both classic Outlook and the new Outlook for Windows, as well as Outlook on the web (OWA) and Outlook mobile apps." },
      { q: "Can my IT admin deploy this to all Outlook 365 users?", a: "Yes. With our Team plan, admins can create and manage signatures centrally. The HTML can also be deployed via Microsoft 365 admin tools or third-party signature management." },
      { q: "Why does my current signature look different in Outlook 365 web vs desktop?", a: "Outlook 365 web and desktop use different HTML rendering engines. NeatStamp's table-based approach works in both because it uses only universally supported HTML elements." },
    ],
  },
  {
    slug: "email-signature-examples-with-logo",
    title: "Examples with Logo",
    metaTitle: "Email Signature Examples with Logo (2026) — Inspiration & Templates | NeatStamp",
    metaDescription: "See 10+ email signature examples with company logos and headshots. Get inspired and create your own logo signature for free. Works in Gmail & Outlook.",
    h1: "Email Signature Examples with Logo",
    intro: "Need inspiration for your email signature with a logo? Browse our curated examples showing how professionals across industries use logos and headshots in their email signatures. Then create your own in 60 seconds with NeatStamp.",
    steps: [
      { title: "Browse examples below", description: "See how different professionals use logos — from corporate to creative, headshot to company logo." },
      { title: "Choose your approach", description: "Company logo, personal headshot, or both? Pick what fits your brand." },
      { title: "Create yours", description: "Use NeatStamp's free editor to upload your logo and build your signature." },
      { title: "Copy and send", description: "Your logo signature is ready. Copy and paste into your email client." },
    ],
    features: [
      "10+ curated email signature examples with logos",
      "Examples for different industries and roles",
      "Company logo and headshot examples",
      "Square, circular, and rectangular logo formats",
      "Free to create your own logo signature",
      "All examples work in Gmail, Outlook, and Apple Mail",
    ],
    faq: [
      { q: "Should I use my company logo or my headshot?", a: "If you're representing a company, use the company logo. If you're a freelancer or consultant, use a professional headshot — it builds personal trust. Some signatures include both." },
      { q: "What's the best logo size for email signatures?", a: "Keep your logo between 70-100px in width or height. Larger logos can trigger spam filters and look unprofessional. NeatStamp automatically optimizes your logo size." },
      { q: "Will my logo be blurry in the signature?", a: "No. Upload a high-resolution logo (at least 200x200px) and NeatStamp will resize it crisply. We use optimized image compression to keep quality high and file size low." },
    ],
  },
  {
    slug: "small-business-email-signature",
    title: "Small Business",
    metaTitle: "Email Signatures for Small Business — Free Generator | NeatStamp",
    metaDescription: "Create professional email signatures for your small business. Free for individuals, team plans for 5+ employees. Consistent branding on every email.",
    h1: "Email Signatures for Small Business",
    intro: "Every email your small business sends is a branding opportunity. With NeatStamp, you can create professional, consistent email signatures for your entire team — from the founder to the newest hire. Free for individuals, affordable team plans when you grow.",
    steps: [
      { title: "Create your signature", description: "Start with the founder or owner's signature. Enter company details, upload your logo, choose brand colors." },
      { title: "Standardize the template", description: "Pick a template that represents your brand. Corporate for law firms, Modern for tech startups, Creative for agencies." },
      { title: "Roll out to your team", description: "Share the template with employees. Each person fills in their own name and title." },
      { title: "Manage centrally (optional)", description: "With the Team plan, manage all signatures from one dashboard. Update once, deploy to everyone." },
    ],
    features: [
      "Free for individual use — perfect for solo entrepreneurs",
      "Team plan at $3/user/month for consistent company branding",
      "Company logo and brand color integration",
      "Professional templates suited for different industries",
      "Central management dashboard for team signatures",
      "Works in Gmail, Outlook, and Google Workspace",
    ],
    faq: [
      { q: "Is NeatStamp free for small businesses?", a: "Yes. Each employee can create their own signature for free. If you want central management and brand enforcement, the Team plan starts at $3/user/month (minimum 5 users)." },
      { q: "How do I ensure brand consistency across my team?", a: "With the free tier, share a screenshot of the approved design and let each person recreate it. With the Team plan, create one template and deploy it to everyone — ensuring identical branding." },
      { q: "Can I add a company-wide promotional banner?", a: "Yes. With NeatStamp Pro, you can add a CTA banner to promote events, offers, or new products. Update it once and it appears in all signatures." },
    ],
  },
];
